module.exports = {
  account: {
    ERROR_ACCOUNT_VALIDATION: "Thiếu thông tin đăng nhập",
    LOGIN_SUCCESSFULL: "Đăng nhập thành công",
    ERROR_ACCOUNT_LOGIN: "Tên đăng nhập hoặc tài khoản không đúng",
    ERROR_ACCOUNT_NOT_FIND: "Không tìm thấy tài khoản",
    ERROR_ACCOUNT_UNAUTHORIZATION:
      "Tài khoản không có đủ quyền hạn thực hiện chức năng này",
    ERROR_ACCOUNT_TIME_BAN: "Thời gian khóa tối đa là 576 giờ",
    ERROR_ACCOUNT_BANNED: "Tài khoản này đang bị khóa",
    BAN_SUCCESSFULL: "Khóa tài khoản thành công",
    ERROR_BAN_VALIDATION: "Thiếu dữ liệu hoặc định dạng không đúng",
    ERROR_DATA_VALIDATION: "Thiếu dữ liệu gửi về",
    SEND_CODE: "Đã gửi mã xác nhận",
    CODE_TIMED: "Mã đã hết hạn",
    ERROR_CODE: "Mã không đúng",
    CHANGE_PASSWORD_SUCCESSFULL: "Thay đổi mật khẩu thành công",
    NEW_PASSWORD_VALIDATION: "Mật khẩu mới không được bỏ trống",
    OLD_PASSWORD_WRONG: "Mật khẩu cũ không chính xác!",
    OLD_PASSWORD_VALIDATION: "Thiếu mật khẩu cũ!",
    ERROR_ACCOUNT_EXISTED: "Tên tài khoản đã tồn tại!",
    ERROR_EMAIL_EXISTED: "Email này đã được sử dụng!",
    REGISTER_SUCCESSFULL: "Tạo mới tài khoản thành công",
    ERROR_REGISTER_VALIDATION: "Thiếu dữ liệu để tạo tài khoản",
    ERROR_OTHER: "Something wrong",
    GET_SUCCESSFULL: "Lấy thông tin thành công",
    NOT_KEYWORD_SEARCH: "Chưa có từ khóa tìm kiếm",
    UPDATE_SUCCESSFULL: "Cập nhật thành công",
    UPDATE_FAILED: "Cập nhật thất bại",
    VALIDATION_REQUIRED: "Yêu cầu bắt buộc",
    UNLOCK_SUCCESSFULL: "Mở khóa tài khoản thành công",
    LOCK_SUCCESSFULL: "Khóa vĩnh viễn tài khoản thành công",
  },
  bookmark: {},
  comment: {},
  feedback: {},
  follow_account: {},
  follow_tag: {},
  image: {},
  information: {},
  notification: {},
  post: {},
  role: {},
  tag: {},
  vote: {},
};
